### ISSUE TITLE
Where is the assignment 3 html?

### ISSUE THREAD

**Issue by HarrisonJackson** [smu-gui-spring-2015/Nchaos#4]
@Nchaos can you take the assignment3 wire frame you did and convert it to a valid html landing page? 

I'll update your grade once you've added that.

**Comment by difnicolas** [comment]
Im not nchaos... im difnicolas.

**Comment by HarrisonJackson** [comment]
See my email about unsubscribing from classmate repos.

**Comment by Nchaos** [comment]
http://lyle.smu.edu/~nhchao/
or are you talking about the paper prototype? (A3.png)
